## Numpy 

In [26]:
import numpy as np
l1=range(1000)
import sys
import time
sys.getsizeof(9)



24

In [27]:
sys.getsizeof(9)*len(l1)

24000

In [33]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [35]:
type(a)

numpy.ndarray

In [36]:
a[3]

3

In [37]:


a=np.arange(1000)
a.itemsize


4

In [38]:
a.size

1000

In [39]:
a.itemsize*a.size

4000

In [2]:
import numpy as np
import sys
import time

size=100000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
l2=[x+y for x,y in zip(l1,l2)]
print('list took:',(time.time()-start)*1000)

start=time.time()

a=a1+a2
print('numpy took:',(time.time()-start)*1000)


('list took:', 109.00020599365234)
('numpy took:', 0.0)


In [3]:
import numpy 
a=np.array(10)
a

array(10)

In [6]:
import numpy as np
cvalues=[20,3,4,5,6,7,8,65]
c=np.array(cvalues)
np.array
print(c)



[20  3  4  5  6  7  8 65]


In [7]:
type(c)

numpy.ndarray

In [8]:
c=np.array([1,2,3])
c.ndim

1

In [9]:
c.dtype

dtype('int32')

## For 2D,3D-Matrix

In [10]:
c=np.array([[],[]])
c.ndim

2

In [11]:
c=np.array([[[],[]],[[],[]],[[],[]]])
c.ndim

3

In [12]:
c=np.array([[1,2,3,4],[5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Slicing 

In [13]:
c[1][0]

5

In [14]:
c[1][1]

6

In [18]:
c[0][0]

1

In [16]:
c=np.array([[1,2,3],[5,6,7,8]])
c

array([list([1, 2, 3]), list([5, 6, 7, 8])], dtype=object)

In [6]:
c=np.array([[1,2,3,4],[5,6,7,8]])      
c[1,1]

6

In [7]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
 c[0,0:]

array([1, 2, 3, 4])

In [9]:
c[0,0::3]

array([1, 4])

In [10]:
c[0:,0::3]

array([[1, 4],
       [5, 8]])

In [12]:
lin=np.linspace(1,10,3)

In [13]:
lin

array([  1. ,   5.5,  10. ])

In [14]:
lin=np.linspace(0,100,12)

In [15]:
lin

array([   0.        ,    9.09090909,   18.18181818,   27.27272727,
         36.36363636,   45.45454545,   54.54545455,   63.63636364,
         72.72727273,   81.81818182,   90.90909091,  100.        ])

In [16]:
lin=np.linspace(1,10,3,endpoint=True)

In [17]:
lin

array([  1. ,   5.5,  10. ])

In [18]:
l,s=np.linspace(1,10,5,endpoint=True,retstep=True)

In [20]:
l

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [21]:
A=np.array([[3.4,8,7],[1.1,-7,8],[2,3,4]])

In [23]:
A[0:0]

array([], shape=(0L, 3L), dtype=float64)

In [24]:
A[0:3:2,0:3:2]

array([[ 3.4,  7. ],
       [ 2. ,  4. ]])