## Numpy 

In [6]:
import numpy as np
cvalues=[20,3,4,5,6,7,8,65]
c=np.array(cvalues)
np.array
print(c)



[20  3  4  5  6  7  8 65]


In [7]:
type(c)

numpy.ndarray

In [8]:
c=np.array([1,2,3])
c.ndim

1

In [9]:
c.dtype

dtype('int32')

## For 2D,3D-Matrix

In [10]:
c=np.array([[],[]])
c.ndim

2

In [11]:
c=np.array([[[],[]],[[],[]],[[],[]]])
c.ndim

3

In [12]:
c=np.array([[1,2,3,4],[5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Slicing 

In [13]:
c[1][0]

5

In [14]:
c[1][1]

6

In [18]:
c[0][0]

1

In [16]:
c=np.array([[1,2,3],[5,6,7,8]])
c

array([list([1, 2, 3]), list([5, 6, 7, 8])], dtype=object)

In [17]:
c=np.array([[1,2,3,4],[5,6,7,8]])
	       
c[1,1]

6

In [19]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
 c[0,0:]

array([1, 2, 3, 4])

In [21]:
c[0,0::3]

array([1, 4])

In [22]:
c[0:,0::3]

array([[1, 4],
       [5, 8]])